# Generated by Django 6.1.1 on 2026-09-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatura (°C)')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Velocidad del Viento (km/h)')),
                ('is_successful', models.BooleanField(default=True, verbose_name='Activo')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('farm_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_logs', to='agronomy.farmfield')),
            ],
        ),
    ]
