# Generated by Django 6.1.1 on 2026-09-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agronomy', '0002_weatherlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlog',
            name='is_successful',
            field=models.BooleanField(default=True),
        ),
    ]
